### ISSUE TITLE
Django 1.7 compatibility

### ISSUE THREAD

**Issue by benrxv** [pinax/pinax-ratings#12]
simplejson was deprecated in django version 1.5: https://docs.djangoproject.com/en/dev/releases/1.5/#system-version-of-simplejson-no-longer-used
In 1.7, it appears to be unsupported.  Instead, they have a new JsonResponse object (they no longer use mimetype either).  If you'd like to add a django-1.7 branch, I can submit a pull request.

**Comment by paltman** [comment]
@benrxv please do send a PR, you can send it to `master`
