### ISSUE TITLE
Example code for HTML form or HTML request based rating instead of Ajax

### ISSUE THREAD

**Issue by Logmytech** [pinax/pinax-ratings#40]
I'm trying to rate on a modified version of pinax-ratings https://github.com/Logmytech/pinax-UpvoteDownvote.

But I'm getting 403 error on rating in the django console. This seems to be a CSRF error, but I have no way to know.

I'm not good with JS.

Can anyone give code for doing requests directly from HTML. It'd help my debugging and implementing of pinax-upvotesdownvotes.

For example code for giving 1 star would be helpful, since I have -1,0,1 as ratable values in my project.

**Comment by KatherineMichel** [comment]
@Logmytech Sorry for the late reply. I think you would be better off to join our Slack and ask in help channel, if you still want to pursue this. Otherwise, feel free to close.
