### ISSUE TITLE
Error when creating new instance for model that agon-ratings is applied.

### ISSUE THREAD

**Issue by tyler46** [pinax/pinax-ratings#6]
Hi,

I am using agon-ratings for a model in my project. When I try to create a new model instance I get "Field 'rating_votes' doesn't have a default value ". Is there anything that I have missed during the agon-rating setupe?

**Comment by ossanna16** [comment]
@tyler46 Has this issue been resolved by now? It's quite old so I was wondering.

**Comment by tyler46** [comment]
Hi @ossanna16, I have implemented the rating for my model in another way. Since I have opened this issue 2 years ago, I am not sure if it was my fault during the setup. Have you tried yourself?

**Comment by ossanna16** [comment]
@tyler46 Awesome! I haven't tried myself, I just looked through all issues and PRs yesterday in order to clean up our repositories a little bit :) Would you still like for someone to look into this or is it okay if I close this issue?

**Comment by tyler46** [comment]
I am ok, you can close this issue :)

**Comment by ossanna16** [comment]
👍
