### ISSUE TITLE
Updating PyPi version

### ISSUE THREAD

**Issue by predatell** [pinax/pinax-ratings#9]
Can you update app on pypi?

**Comment by itsMagondu** [comment]
Thanks for the amazing app guys. Could you please update the pypi version? We keep pulling the version from 2011

**Comment by itsMagondu** [comment]
Or are we supposed to be using this https://pypi.python.org/pypi/pinax-ratings/?

**Comment by paltman** [comment]
@itsMagondu @predatell yes, it was renamed
